services:
  discovery-service:
    image: discovery-service
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:9999

  config-service:
    image: config-service
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    ports:
      - "9999:9999"
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 5

    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:9999


  customer-service:
    image: customer-service
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    container_name: customer-service
    ports:
      - "8081:8081"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:9999

  account-service:
    image: account-service
    build:
      context: ./account-service
      dockerfile: Dockerfile
    container_name: account-service
    ports:
      - "8082:8082"
    depends_on:
      customer-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 5
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:9999
  gateway-service:
    image: gateway-service
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8888:8888"
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      retries: 5

    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka/
      - CONFIG_SERVER_URL=http://config-service:9999

  front-end-angular:
    build: ./angular-front-end
    container_name: front-end-angular
    ports:
      - '82:80'

  front-end-react:
    build: ./react-front-end
    container_name: front-end-react
    ports:
      - '83:80'